apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
   - rolearn: arn:aws:iam::055759662340:role/UdacityFlaskDeployCBKubectlRole
       username: build
       groups:
         - system:masters